### ISSUE TITLE
Translation: Spanish is incorrect. "ahorrar", "respaldar"

### ISSUE THREAD

**Issue by christopherowenowens** [breez/Breez-Translations#25]
### General Description

Spanish language translation is incorrect. 

"Ahorrar" -> "Guardar". Ahorrar means to save money, discount; guardar means to save settings.
"Respaldar" seems very unusual for "backup", usually respaldar means to "back" something as in support it; you usually hear "copiar de seguridad".

However, I am not a native speaker, so there may be other translations that are incorrect.
Instead of me doing a PR for just the one ahorrar -> guardar, I am opening this for a more fluent speaker to review and adjust. If no one gets to it this week, I'll try to make the PRs.

### How To Reproduce?

1. Open top left folder from home screen
2. Click on profile picture 
3. Options are "Cancelar" or "Ahorrar". Should be Guardar.

### Screenshots
N/A

### Logs
N/A

### What type of machine are you observing the error on?
Mobile Phone - Android

### Operating System
Android 11

### Breez Version
0.16.4-beta; 2023-09-21

**Comment by ademar111190** [comment]
Thank you @christopherowenowens 
"Guardar" sounds better in that context for me, but I'm in the same boat as you as Spanish is not my native language.

I'll wait for a native speaker to give an opinion here. This translation has been reviewed for a few native speakers already, but that can be something they missed for sure.

**Comment by anon-dev-gh** [comment]
Just opened a PR, I'm a native spanish spaker and yes, the correct translation is `"GUARDAR"`

**Comment by ademar111190** [comment]
Fixed at https://github.com/breez/Breez-Translations/pull/27
Thank you very much @anon-dev-gh
